# Generated by Django 4.2.3 on 2023-09-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=100)),
                ('Sid', models.IntegerField()),
                ('Semail', models.EmailField(max_length=254)),
            ],
        ),
    ]
